name: regenerate dist after dependabot updates
on:
  pull_request:
    types: [opened, synchronize]
    paths: &paths
      - package*.json
      - tsconfig.json
      - src/**
  push:
    branches:
      - main
    paths: *paths

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          persist-credentials: true
          token: ${{ secrets.BOT_TOKEN }}
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version-file: "package.json"
      - run: npm ci
      - run: npm start
      - uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7
        with:
          commit_message: regenerate dist
          
              
